# service description
services:
  # cloudflare tunnel
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    #build:
    #  context: ./src
    #  dockerfile: ./Dockerfile
    container_name: cloudflare-tunnel
    environment:
      - "TUNNEL_TOKEN=${TOKEN}"
      - "HOSTNAME=${HOSTNAME}"
    hostname: ${HOSTNAME}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    network_mode: "host"
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/hosts:/etc/hosts
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      # enbale watchtower updates
      - "com.centurylinklabs.watchtower.enable=true"
